name: Python Package with conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "sbpy"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda install -c defaults -c conda-forge -c astropy -c moeyensj --file requirements.txt --yes
      - name: Install THOR
        run: |
          python setup.py install
      - name: Test with pytest
        run: |
          pytest . --cov=.